### ISSUE TITLE
Better sessions

### ISSUE THREAD

**Issue by natew** [natew/obtvse#24]
Placeholder for discussion on best way to implement sessions or users.

Also as of e9f5ba2ee9ae53e148eb64d64908affad657bc86 is_admin? isn't working.

**Comment by cobyism** [comment]
For starters I don't think there is a real need to implement multiple users in this thing yet, but by the same token it'd be nice not to have the user/pass stored in plaintext in the config file.

One simple solution would be to just use something like [Devise](https://github.com/plataformatec/devise) and add creating an initial admin user to a rake task when you first install/push to Heroku. You'd need to turn off registration and so forth so that not just anyone could register an account and create posts, and you'd also want to try and figure out a way of avoiding there being a widely-known default password on Obtvse blogs which could mean that accessing freshly installed blogs of other people is trivial if they don't change their password (maybe by having them choose a password as part of the rake task?).

Things like Devise might be a bit much though, and I'm sure you'd be able to do something similar without the extra dependancy/overhead.

**Comment by natew** [comment]
I was looking into [Sorcery](https://github.com/NoamB/sorcery) as it seems simpler for what we need

On a sort of related note I would prefer to have an setup up process once you've installed it that guides you through your account, site details and such.  One page form would be fine.  Plus a way to edit it in admin.  As long as it's kept very simple it would be nice.

**Comment by cobyism** [comment]
Sorcery looks pretty neat. If it plays well with oauth then you could even have it so that people log into their own blog with their Twitter/Github/whatever account (which may, or may not be a good idea).

Wizard page is a much more user friendly way to do it, however you're then unable to check config settings (like analytics code, contact email, site title and so forth) into version control as they're no longer in the text file, and if you need to migrate between production instances downstream you then get into pushing/pulling/exporting databases, which is considerably more complicated than editing a text file. You'd be doing that anyway with your posts I guess, but it's just a trade-off you'll have to keep in mind.

**Comment by krainboltgreene** [comment]
Plus one for Sorcery, I've found it much easier to use.

There's also a gem for Wizard-like forms, I can't remember the name.
