### ISSUE TITLE
Google analytics doesn't recognize my website

### ISSUE THREAD

**Issue by Oliviergg** [natew/obtvse#58]
# Issue

I have changed config.yml to configure item named google_analytics_id with my id, but google analytics doesn't recognize my website.
# Workaround

So i changed the google analytics script in app/views/layout/application?html.erb with the standard code given by google

```
<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', '<%= CONFIG['google_analytics_id'] %>']);
_gaq.push(['_trackPageview']);
(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
```

</script>
And Google Analytics instantly recognize my site.

**Comment by natew** [comment]
Not having this issue with my version, anyone else?

**Comment by webjames** [comment]
i have just installed it and i am not having this problem. i'm not sure what is meant by 'doesn't recognize my website', it could be that since the web property in google analytics hadn't received any data, Analytics thought that the ID wasn't being used?
i've just had a look in the GA interface and all i can find is within the Admin > tracking code section a line like this: 'Tracking Status: Receiving Data'.

EDIT: Google recommends that the tracking script is placed immediately before the closing head tag, without this, and the asynchronous snippet as defined by Google Webmaster Tools verification by the Analytics snippet is not possible, this might have been the issue.
